apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-checker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssl-checker
  template:
    metadata:
      labels:
        app: ssl-checker
    spec:
      containers:
      - name: ssl-checker
        image: gokalpmeric/sslchecker:0.0.3
        ports:
        - containerPort: 5000
