apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ssl-checker-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-checker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssl-checker
  template:
    metadata:
      labels:
        app: ssl-checker
    spec:
      containers:
      - name: ssl-checker
        image: gokalpmeric/sslchecker:0.0.4
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: data
          mountPath: /app/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: ssl-checker-pvc
